<?php
/**
 * ApiException
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Recebimentos Pix
 *
 * Recebimentos Pix
 *
 * OpenAPI spec version: 2.41.15
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.35
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client;

use \Exception;

/**
 * ApiException Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class HeaderSelector
{


    /**
     * @param string[] $config 
     * @param string[] $headersInput
     * @return array
     */
    public function aplicarHeadersITAU($config, $headersInput)
    {

        echo "* HeaderSelector->aplicarHeadersITAU()\n";
        
       // PRODUCAO
       if($config->isModoProducao()){
            echo "* Modo Producao\n";
            echo "* Aplicando cert e ssl_key no header da requisicao\n";
            if ($config->getPathCertificado() !== null && $config->getPathPrivateKey() !== null) {
                $headersInput['cert'] = $config->getPathCertificado();
                $headersInput['ssl_key'] = $config->getPathPrivateKey();
            }else{
                throw new ApiException(
                    "* Modo Producao: Path p/ Certificado e path p/ Private Key obrigatorio.",
                    0,
                    null,
                    null
                );
            }
            echo "* Incluindo header Authorization Bearer";
            if($config->getAccessToken()!==null || $config->getAccessToken()!==''){
                $headersInput['Authorization'] = 'Bearer ' . $config->getAccessToken();
            }

        }else{
            // SANDBOX
            echo "* Modo SANDBOX\n";
            echo "* Aplicando header x-sandbox-token\n";
            if($config->getAccessToken()!==null || $config->getAccessToken()!==''){
                $headersInput['x-sandbox-token'] = $config->getAccessToken();
            }
        }
       
        echo "* aplicando header x-itau-apikey com o valor do client_id \n";
        $headersInput['x-itau-apikey'] = isset($config->apiKeys['client_id']) ? $config->apiKeys['client_id'] : 123;
        
        return $headersInput;
    }

    /**
     * @param string[] $accept
     * @param string[] $contentTypes
     * @return array
     */
    public function selectHeaders($accept, $contentTypes)
    {
        $headers = [];

        $accept = $this->selectAcceptHeader($accept);
        if ($accept !== null) {
            $headers['Accept'] = $accept;
        }

        $headers['Content-Type'] = $this->selectContentTypeHeader($contentTypes);
        return $headers;
    }

    /**
     * @param string[] $accept
     * @return array
     */
    public function selectHeadersForMultipart($accept)
    {
        $headers = $this->selectHeaders($accept, []);

        unset($headers['Content-Type']);
        return $headers;
    }

    /**
     * Return the header 'Accept' based on an array of Accept provided
     *
     * @param string[] $accept Array of header
     *
     * @return string Accept (e.g. application/json)
     */
    private function selectAcceptHeader($accept)
    {
        if (count($accept) === 0 || (count($accept) === 1 && $accept[0] === '')) {
            return null;
        } elseif (preg_grep("/application\/json/i", $accept)) {
            return 'application/json';
        } else {
            return implode(',', $accept);
        }
    }

    /**
     * Return the content type based on an array of content-type provided
     *
     * @param string[] $contentType Array fo content-type
     *
     * @return string Content-Type (e.g. application/json)
     */
    private function selectContentTypeHeader($contentType)
    {
        if (count($contentType) === 0 || (count($contentType) === 1 && $contentType[0] === '')) {
            return 'application/json';
        } elseif (preg_grep("/application\/json/i", $contentType)) {
            return 'application/json';
        } else {
            return implode(',', $contentType);
        }
    }
}

