<?php
/**
 * CobrancasParametrosTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Recebimentos Pix
 *
 * Recebimentos Pix
 *
 * OpenAPI spec version: 2.41.15
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.35
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * CobrancasParametrosTest Class Doc Comment
 *
 * @category    Class
 * @description CobrancasParametros
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CobrancasParametrosTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CobrancasParametros"
     */
    public function testCobrancasParametros()
    {
    }

    /**
     * Test attribute "inicio"
     */
    public function testPropertyInicio()
    {
    }

    /**
     * Test attribute "fim"
     */
    public function testPropertyFim()
    {
    }

    /**
     * Test attribute "txid"
     */
    public function testPropertyTxid()
    {
    }

    /**
     * Test attribute "cpf"
     */
    public function testPropertyCpf()
    {
    }

    /**
     * Test attribute "cnpj"
     */
    public function testPropertyCnpj()
    {
    }

    /**
     * Test attribute "location_presente"
     */
    public function testPropertyLocationPresente()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "paginacao"
     */
    public function testPropertyPaginacao()
    {
    }
}
