<?php
/**
 * CobrancaVencimento403ViolacoesTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Recebimentos Pix
 *
 * Recebimentos Pix
 *
 * OpenAPI spec version: 2.41.15
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.35
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * CobrancaVencimento403ViolacoesTest Class Doc Comment
 *
 * @category    Class
 * @description CobrancaVencimento403Violacoes
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CobrancaVencimento403ViolacoesTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CobrancaVencimento403Violacoes"
     */
    public function testCobrancaVencimento403Violacoes()
    {
    }

    /**
     * Test attribute "razao"
     */
    public function testPropertyRazao()
    {
    }

    /**
     * Test attribute "propriedade"
     */
    public function testPropertyPropriedade()
    {
    }

    /**
     * Test attribute "valor"
     */
    public function testPropertyValor()
    {
    }
}
