<?php
/**
 * CobrancasVencimentoCobsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Recebimentos Pix
 *
 * Recebimentos Pix
 *
 * OpenAPI spec version: 2.41.15
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.35
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * CobrancasVencimentoCobsTest Class Doc Comment
 *
 * @category    Class
 * @description CobrancasVencimentoCobs
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CobrancasVencimentoCobsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CobrancasVencimentoCobs"
     */
    public function testCobrancasVencimentoCobs()
    {
    }

    /**
     * Test attribute "calendario"
     */
    public function testPropertyCalendario()
    {
    }

    /**
     * Test attribute "devedor"
     */
    public function testPropertyDevedor()
    {
    }

    /**
     * Test attribute "loc"
     */
    public function testPropertyLoc()
    {
    }

    /**
     * Test attribute "valor"
     */
    public function testPropertyValor()
    {
    }

    /**
     * Test attribute "chave"
     */
    public function testPropertyChave()
    {
    }

    /**
     * Test attribute "solicitacao_pagador"
     */
    public function testPropertySolicitacaoPagador()
    {
    }

    /**
     * Test attribute "info_adicionais"
     */
    public function testPropertyInfoAdicionais()
    {
    }

    /**
     * Test attribute "txid"
     */
    public function testPropertyTxid()
    {
    }

    /**
     * Test attribute "revisao"
     */
    public function testPropertyRevisao()
    {
    }

    /**
     * Test attribute "recebedor"
     */
    public function testPropertyRecebedor()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "pix_copia_e_cola"
     */
    public function testPropertyPixCopiaECola()
    {
    }

    /**
     * Test attribute "pix"
     */
    public function testPropertyPix()
    {
    }
}
