<?php
/**
 * DevolucaoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Recebimentos Pix
 *
 * Recebimentos Pix
 *
 * OpenAPI spec version: 2.41.15
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.35
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * DevolucaoTest Class Doc Comment
 *
 * @category    Class
 * @description Devolucao
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DevolucaoTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Devolucao"
     */
    public function testDevolucao()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "rtr_id"
     */
    public function testPropertyRtrId()
    {
    }

    /**
     * Test attribute "valor"
     */
    public function testPropertyValor()
    {
    }

    /**
     * Test attribute "natureza"
     */
    public function testPropertyNatureza()
    {
    }

    /**
     * Test attribute "descricao"
     */
    public function testPropertyDescricao()
    {
    }

    /**
     * Test attribute "horario"
     */
    public function testPropertyHorario()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "motivo"
     */
    public function testPropertyMotivo()
    {
    }
}
