<?php
/**
 * LocsParametrosTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Recebimentos Pix
 *
 * Recebimentos Pix
 *
 * OpenAPI spec version: 2.41.15
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.35
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * LocsParametrosTest Class Doc Comment
 *
 * @category    Class
 * @description LocsParametros
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class LocsParametrosTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "LocsParametros"
     */
    public function testLocsParametros()
    {
    }

    /**
     * Test attribute "inicio"
     */
    public function testPropertyInicio()
    {
    }

    /**
     * Test attribute "fim"
     */
    public function testPropertyFim()
    {
    }

    /**
     * Test attribute "tx_id_presente"
     */
    public function testPropertyTxIdPresente()
    {
    }

    /**
     * Test attribute "tipo_cob"
     */
    public function testPropertyTipoCob()
    {
    }

    /**
     * Test attribute "paginacao"
     */
    public function testPropertyPaginacao()
    {
    }
}
