<?php
/**
 * LoteCobrancaVencimentoIdGetResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Recebimentos Pix
 *
 * Recebimentos Pix
 *
 * OpenAPI spec version: 2.41.15
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.35
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * LoteCobrancaVencimentoIdGetResponseTest Class Doc Comment
 *
 * @category    Class
 * @description LoteCobrancaVencimentoIdGetResponse
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class LoteCobrancaVencimentoIdGetResponseTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "LoteCobrancaVencimentoIdGetResponse"
     */
    public function testLoteCobrancaVencimentoIdGetResponse()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "criacao"
     */
    public function testPropertyCriacao()
    {
    }

    /**
     * Test attribute "descricao"
     */
    public function testPropertyDescricao()
    {
    }

    /**
     * Test attribute "cobsv"
     */
    public function testPropertyCobsv()
    {
    }
}
