<?php
/**
 * PixTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Recebimentos Pix
 *
 * Recebimentos Pix
 *
 * OpenAPI spec version: 2.41.15
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.35
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * PixTest Class Doc Comment
 *
 * @category    Class
 * @description Pix
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PixTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Pix"
     */
    public function testPix()
    {
    }

    /**
     * Test attribute "end_to_end_id"
     */
    public function testPropertyEndToEndId()
    {
    }

    /**
     * Test attribute "txid"
     */
    public function testPropertyTxid()
    {
    }

    /**
     * Test attribute "valor"
     */
    public function testPropertyValor()
    {
    }

    /**
     * Test attribute "componentes_valor"
     */
    public function testPropertyComponentesValor()
    {
    }

    /**
     * Test attribute "chave"
     */
    public function testPropertyChave()
    {
    }

    /**
     * Test attribute "horario"
     */
    public function testPropertyHorario()
    {
    }

    /**
     * Test attribute "info_pagador"
     */
    public function testPropertyInfoPagador()
    {
    }

    /**
     * Test attribute "devolucoes"
     */
    public function testPropertyDevolucoes()
    {
    }
}
