<?php
/**
 * LoteDeCobranaComVencimentoLotecobvApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Recebimentos Pix
 *
 * Recebimentos Pix
 *
 * OpenAPI spec version: 2.41.15
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.35
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * LoteDeCobranaComVencimentoLotecobvApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class LoteDeCobranaComVencimentoLotecobvApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for getlotecobv
     *
     * .
     *
     */
    public function testGetlotecobv()
    {
    }

    /**
     * Test case for getlotecobvid
     *
     * .
     *
     */
    public function testGetlotecobvid()
    {
    }

    /**
     * Test case for patchlotecobvid
     *
     * .
     *
     */
    public function testPatchlotecobvid()
    {
    }

    /**
     * Test case for putlotecobvid
     *
     * .
     *
     */
    public function testPutlotecobvid()
    {
    }
}
